/* CUSTOMER Types */
export const GET_CUSTOMER = "GET_CUSTOMER";
export const ADD_CUSTOMER = "ADD_CUSTOMER";
export const DELETE_CUSTOMER = "DELETE_CUSTOMER";
export const CUSTOMER_FAIL = "CUSTOMER_FAIL";
export const UPDATE_CUSTOMER = "UPDATE_CUSTOMER";
export const CUSTOMER_CREATED = "CUSTOMER_CREATED";
export const CUSTOMER_DELETED = "CUSTOMER_DELETED";

/* FILTER Types */
export const GET_FILTER = "GET_FILTER";
export const ADD_FILTER = "ADD_FILTER";
export const FILTER_DELETED = "FILTER_DELETED";
export const CUSTOMER_FILTER= "FILTER_FAIL";
export const UPDATE_FILTER = "UPDATE_FILTER";
export const FILTER_CREATED = "FILTER_CREATED";
export const FILTER_FAIL = "FILTER_FAIL";



/* AUDIENCE Types */
export const GET_COMMUNICATION_LOG = "GET_COMMUNICATION_LOG";
export const COMMUNICATION_LOG_CREATED = "COMMUNICATION_LOG_CREATED";
export const ADD_COMMUNICATION_LOG = "ADD_COMMUNICATION_LOG";
export const DELETE_COMMUNICATION_LOG = "DELETE_COMMUNICATION_LOG";
export const COMMUNICATION_LOG_FAIL = "COMMUNICATION_LOG_FAIL";
export const UPDATE_COMMUNICATION_LOG = "UPDATE_COMMUNICATION_LOG";
export const COMMUNICATION_LOG_ERROR = "COMMUNICATION_LOG_ERROR";
export const COMMUNICATION_LOG_DELETED = "COMMUNICATION_LOG_DELETED";

/* ERROR Types */
export const GET_ERROR = 'GET_ERROR';
export const CLEAR_ERROR = 'CLEAR_ERROR';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const GET_ERRORS = 'GET_ERRORS';